name: cv-env
channels:
  - conda-forge
dependencies:
  - python=3.10.19
  - opencv=4.12.0
  - dlib=20.0.0
  - face_recognition=1.3.0
  - python-dotenv=1.2.1
  - pillow=12.1.0
  - pip
  - pip:
    - numpy==1.26.4
    - PyOpenGL==3.1.7
    - PyOpenGL-accelerate==3.1.7
    - async-timeout==5.0.1
    - glfw==2.7.0
    - redis==6.4.0